### ISSUE TITLE
closeio Closeio Lead Id is empty

### ISSUE THREAD

**Issue by lookitsbeau** [activeprospect/leadconduit-integration-closeio#1]
We need to capture the `id` returned by Closeio 

https://next.leadconduit.com/events/54fa2b7bd8ee16952ef3a977?event_id=54fa2b7bd8ee16952ef3a97e

**Comment by cgrayson** [comment]
If you look further down the list of data appended on that lead, it _is_ capturing it… twice, in fact:

```
closeio Id         lead_WilQxr0oCPdvmlj18CHSNlZqR9BlzYVYwYZVmG6YSQq
closeio Lead Id    lead_WilQxr0oCPdvmlj18CHSNlZqR9BlzYVYwYZVmG6YSQq
```

But the namespacing isn't right, obviously, as the subsequent add note failed. I'll check it out.

**Comment by cgrayson** [comment]
This part is actually working correctly. The problem in that flow is that you mapped a wrong value as the Close.io lead id in the add-note step. In that case, no mapping was required at all, the note step gets that ID automatically. So I removed that mapping, and now it works. 

There are still related problems - it shouldn't have offered a "wrong value" for you to map. Working on that next, but [this is working](https://next.leadconduit.com/events/5503116a01578a64565f614e?event_id=5503116b01578a64565f6155).
